services:
  mlops-iris-api:
    build:
      context: ./src/api/
      dockerfile: Dockerfile
    volumes:
      - ./models/model.joblib:/app/model.joblib
    expose:
        - "8000"
    ports:
        - "8000:8000"
  nginx:
    build:
      context: .
      dockerfile: deployments/nginx/Dockerfile
    container_name: nginx_revproxy
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./deployments/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployments/nginx/certs:/etc/nginx/certs:ro
      - ./deployments/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - mlops-iris-api
