    global:
      scrape_interval: 3s

    scrape_configs:
      - job_name: 'nginx-exporter'
        static_configs:
          # Cible à scraper : l'exporter Nginx
          - targets: ['nginx_exporter:9113']
    